{% set name = "con-duct" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/con_duct-{{ version }}.tar.gz
  sha256: 6762fff98ddab55dc18c8f89a6fce7f6b98571e90f1b60412a71c82b0a2b43d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.4.0
    - pip
    - versioningit
  run:
    - python >={{ python_min }}
    - __unix  # Constrain to linux and mac
    - matplotlib
    - PyYaml
    - pyout

test:
  imports:
    - con_duct
  commands:
    - python -m pytest -vv test
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-cov
    - pytest-rerunfailures
    - matplotlib
    # ps is needed for tests, macOS provides by default
    - procps-ng  # [linux]
  source_files:
    - test
    - tox.ini

about:
  home: https://github.com/con/duct/
  summary: Runs a command and collects resource usage metrics
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asmacdo
    - yarikoptic
    - CodyCBakerPhD
