{% set name = "con-duct" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/con_duct-{{ version }}.tar.gz
  sha256: d7c1a5aeb0a6ee18803adef3ecdc61653529ab17846e8a14800be17a8bf50c68

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.4.0
    - pip
  run:
    - python >={{ python_min }}
    - __linux  # Contstrain to linux
    - matplotlib

test:
  imports:
    - con_duct
  commands:
    - python -m pytest -vv test
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-cov
    - matplotlib
  source_files:
    - test
    - tox.ini

about:
  home: https://github.com/con/duct/
  summary: Runs a command and collects resource usage metrics
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asmacdo
    - yarikoptic
    - jwodder
