{% set name = "con-duct" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/con_duct-{{ version }}.tar.gz
  sha256: c785733ce0ddc2baebc1d4f7b6837ac115f72fe9560969e18f1ef6d00fd3fec8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.4.0
    - pip
    - versioningit
  run:
    - python >={{ python_min }}
    - __unix  # Constrain to linux and mac
    - matplotlib
    - PyYaml
    - pyout

test:
  imports:
    - con_duct
  commands:
    - python -m pytest -vv test
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-cov
    - pytest-rerunfailures
    - matplotlib
    # ps is needed for tests, macOS provides by default
    - procps-ng  # [linux]
  source_files:
    - test
    - tox.ini

about:
  home: https://github.com/con/duct/
  summary: Runs a command and collects resource usage metrics
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asmacdo
    - yarikoptic
    - CodyCBakerPhD
